### ISSUE TITLE
Madeleine's Test Issue

### ISSUE THREAD

**Issue by mathdow** [Openscapes/2024-swrcb-spring#10]
## Table Test

| Breakout room members | Github usernames |
| -------- | ------- |
| Madeleine Dow | @mathdow |
| Spencer McLintock | @SpencerMatWB |
| Abbey Warner | @awarner16 |

## Emoji Test

:blush: :+1: 😄 🍃

**Comment by awarner16** [comment]
💯 🏅 ✏️

**Comment by SpencerMatWB** [comment]
|things I like| |things i dont like|
|--------------| |-------------|
|This Table| |proper punctuation|
|Using Tables| |getting kicked out of breakout rooms|

**Comment by SpencerMatWB** [comment]
second try at table making
| things I like | | things i dont like |
| -------------- | | ------------- |
| This Table | | improper punctuation |
| Using Tables | | getting kicked out of breakout rooms |

**Comment by SpencerMatWB** [comment]
third try at table making

| things I like | | things i dont like |
| -------------- | | ------------- |
| This Table | | improper punctuation |
| Using Tables | | getting kicked out of breakout rooms |

**Comment by SpencerMatWB** [comment]
4th try at table making
| things I like | things i dont like |
| -------------- | ------------- |
| This Table | improper punctuation |
| Using Tables | getting kicked out of breakout rooms |

**Comment by mathdow** [comment]
| Hooray!! |
| --------- |
